sllite_panel_Site:
    type: rest
    prefix: /api
    resource: Sllite\PanelBundle\Controller\RestController
    name_prefix: rest_

sllite_panel_Site_html:
    prefix: /
    resource: Sllite\PanelBundle\Controller\SiteController
