sllite_panel_Site:
    type: rest
    prefix: /api
    resource: Sllite\PanelBundle\Controller\RestController
    name_prefix: rest_

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
