Sllite\PanelBundle\Entity\Site:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: domain
    properties:
        name:
            - NotBlank: ~
            - NotNull: ~
            - Length:
                min: 3
                max: 255
                minMessage: "Вы ввели очень короткое имя"
                maxMessage: "Вы ввели очень длинное имя"
        domain:
            - NotBlank: ~
            - NotNull: ~
#            - Length:
#                min: 1
#                max: 255
#                minMessage: "Вы ввели очень короткое доменное имя"
#                maxMessage: "Вы ввели очень длинное доменное имя"
            - Regex:
                pattern: "/([a-zA-Z0-9]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,6}/"
                match: true
                message: "Введён неправильный домен"