Sllite\PanelBundle\Entity\Site:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: domain
    properties:
        name:
            - NotBlank: ~
            - NotNull: ~
            - Length:
                min: 3
                max: 255
                minMessage: "Вы ввели очень короткое имя"
                maxMessage: "Вы ввели очень длинное имя"
        domain:
            - NotBlank: ~
            - NotNull: ~
            - Sllite\PanelBundle\Validator\Constraints\Domain: ~
